### ISSUE TITLE
Service Registry + Config client + OAuth2 client: fails to start with Spring Boot starter parent 1.5.5+

### ISSUE THREAD

**Issue by jrsamson** [pivotal-cf/spring-cloud-services-connector#47] opened 2018-05-08 15:33 UTC
Application has configured OAuth2 as authentication mechanism. After `cf push` and `cf bind-service` - application starts successfully if only ONE is imported - either Service Registry starter or Spring Cloud Config.

If I have them both - App failed to start with this error:

```
2018-04-11T16:54:45.041+02:00 [APP/PROC/WEB/0] [OUT] APPLICATION FAILED TO START 
2018-04-11T16:54:45.041+02:00 [APP/PROC/WEB/0] [OUT] Description: 
2018-04-11T16:54:45.041+02:00 [APP/PROC/WEB/0] [OUT] Parameter 1 of constructor in org.springframework.boot.autoconfigure.security.oauth2.resource.ResourceServerTokenServicesConfiguration$RemoteTokenServicesConfiguration$UserInfoTokenServicesConfiguration required a single bean, but 2 were found: 
2018-04-11T16:54:45.041+02:00 [APP/PROC/WEB/0] [OUT] - eurekaOAuth2ResourceDetails: defined by method 'eurekaOAuth2ResourceDetails' in class path resource [io/pivotal/spring/cloud/service/eureka/EurekaOAuth2AutoConfiguration.class] 
2018-04-11T16:54:45.041+02:00 [APP/PROC/WEB/0] [OUT] - configClientOAuth2ResourceDetails: defined by method 'configClientOAuth2ResourceDetails' in io.pivotal.spring.cloud.service.config.ConfigClientOAuth2BootstrapConfiguration 
2018-04-11T16:54:45.041+02:00 [APP/PROC/WEB/0] [OUT] Action: 
2018-04-11T16:54:45.041+02:00 [APP/PROC/WEB/0] [OUT] Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

Please see attached sample project.

I was able to get the app started successfully with Spring-boot-starter-parent 1.5.4. It Fails for 1.5.5 and later

```
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.4.RELEASE</version>
	</parent>
```

Please advise. 

Thanks.

[pivotal-issue-sample.zip](https://github.com/pivotal-cf/spring-cloud-services-connector/files/1984589/pivotal-issue-sample.zip)

**Comment by csterwa** [comment] 2018-06-25 18:21
@jrsamson I've recreated this issue and we will try to resolve it soon. Sorry for the delay in responding to this issue.

**Comment by csterwa** [comment] 2018-07-18 15:47
Note to self: Verify with SCS Connector 2.0.1.RELEASE and see if this may be resolved.

**Comment by ebarreras** [comment] 2018-07-31 15:40
@csterwa 
I'm also seeing this with Spring Boot 2.0.4.RELEASE, spring-cloud-services-dependencies 2.0.1.RELEASE and spring-cloud-dependencies Finchley.RELEASE.

These are my spring/spring cloud related dependencies (omitting the rest to minimize clutter):

[INFO] +- org.springframework.boot:spring-boot-starter-actuator:jar:2.0.4.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.0.4.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.0.4.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.0.4.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-actuator:jar:2.0.4.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-amqp:jar:2.0.4.RELEASE:compile
[INFO] |  +- org.springframework:spring-messaging:jar:5.0.8.RELEASE:compile
[INFO] |  \- org.springframework.amqp:spring-rabbit:jar:2.0.5.RELEASE:compile
[INFO] |     +- org.springframework.amqp:spring-amqp:jar:2.0.5.RELEASE:compile
[INFO] |     +- org.springframework:spring-tx:jar:5.0.8.RELEASE:compile
[INFO] |     \- org.springframework.retry:spring-retry:jar:1.2.2.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-data-jpa:jar:2.0.4.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-aop:jar:2.0.4.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-jdbc:jar:2.0.4.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-jdbc:jar:5.0.8.RELEASE:compile
[INFO] |  +- org.springframework.data:spring-data-jpa:jar:2.0.9.RELEASE:compile
[INFO] |  |  +- org.springframework.data:spring-data-commons:jar:2.0.9.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-orm:jar:5.0.8.RELEASE:compile
[INFO] |  \- org.springframework:spring-aspects:jar:5.0.8.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.0.4.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.0.4.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.0.4.RELEASE:compile
[INFO] |  +- org.springframework:spring-web:jar:5.0.8.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.0.8.RELEASE:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.0.8.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-security:jar:2.0.4.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:5.0.8.RELEASE:compile
[INFO] |  +- org.springframework.security:spring-security-config:jar:5.0.7.RELEASE:compile
[INFO] |  \- org.springframework.security:spring-security-web:jar:5.0.7.RELEASE:compile
[INFO] +- org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure:jar:2.0.1.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot:jar:2.0.4.RELEASE:compile
[INFO] |  \- org.springframework.boot:spring-boot-autoconfigure:jar:2.0.4.RELEASE:compile
[INFO] +- org.springframework.security.oauth:spring-security-oauth2:jar:2.3.3.RELEASE:compile
[INFO] |  +- org.springframework:spring-beans:jar:5.0.8.RELEASE:compile
[INFO] |  +- org.springframework:spring-core:jar:5.0.8.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.0.8.RELEASE:compile
[INFO] |  +- org.springframework:spring-context:jar:5.0.8.RELEASE:compile
[INFO] |  +- org.springframework.security:spring-security-core:jar:5.0.7.RELEASE:compile
[INFO] +- org.springframework.security:spring-security-jwt:jar:1.0.9.RELEASE:compile
[INFO] +- io.pivotal.spring.cloud:spring-cloud-services-starter-service-registry:jar:2.0.1.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:jar:2.0.0.RELEASE:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-starter:jar:2.0.0.RELEASE:compile
[INFO] |  |  |  \- org.springframework.security:spring-security-rsa:jar:1.0.5.RELEASE:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-netflix-core:jar:2.0.0.RELEASE:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-netflix-eureka-client:jar:2.0.0.RELEASE:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-starter-netflix-archaius:jar:2.0.0.RELEASE:compile
[INFO] |  |  |  +- org.springframework.cloud:spring-cloud-netflix-ribbon:jar:2.0.0.RELEASE:compile
[INFO] |  |  |  +- org.springframework.cloud:spring-cloud-netflix-archaius:jar:2.0.0.RELEASE:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-starter-netflix-ribbon:jar:2.0.0.RELEASE:compile
[INFO] |  +- io.pivotal.spring.cloud:spring-cloud-services-cloudfoundry-connector:jar:2.0.1.RELEASE:compile
[INFO] |  |  +- io.pivotal.spring.cloud:spring-cloud-services-connector-core:jar:2.0.1.RELEASE:compile
[INFO] |  |  |  \- org.springframework.cloud:spring-cloud-connectors-core:jar:2.0.2.RELEASE:compile
[INFO] |  |  \- org.springframework.cloud:spring-cloud-cloudfoundry-connector:jar:2.0.2.RELEASE:compile
[INFO] |  +- io.pivotal.spring.cloud:spring-cloud-services-spring-connector:jar:2.0.1.RELEASE:compile
[INFO] |  |  \- org.springframework.cloud:spring-cloud-spring-service-connector:jar:2.0.2.RELEASE:compile
[INFO] |  \- io.pivotal.spring.cloud:cloudfoundry-certificate-truster:jar:1.0.1.RELEASE:compile
[INFO] +- io.pivotal.spring.cloud:spring-cloud-services-starter-config-client:jar:2.0.1.RELEASE:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-config-client:jar:2.0.0.RELEASE:compile
[INFO] |     +- org.springframework.cloud:spring-cloud-commons:jar:2.0.0.RELEASE:compile
[INFO] |     |  \- org.springframework.security:spring-security-crypto:jar:5.0.7.RELEASE:compile
[INFO] |     \- org.springframework.cloud:spring-cloud-context:jar:2.0.0.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.0.4.RELEASE:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.0.4.RELEASE:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.0.4.RELEASE:test
[INFO] |  +- org.springframework:spring-test:jar:5.0.8.RELEASE:test

**Comment by csterwa** [comment] 2018-10-02 16:18
@jrsamson I am not able to reproduce this with newer versions of the connectors. Are you able to reproduce with `1.6.4.RELEASE` or `2.0.1.RELEASE` of SCS Connectors?

https://github.com/pivotal-cf/spring-cloud-services-connector/releases

**Comment by csterwa** [comment] 2018-11-01 18:03
Closing this issue. Let me know if you would like to reopen.

**Closed by csterwa** 2018-11-01 18:03 UTC
Labels: in progress
